### ISSUE TITLE
Known Issue: Some types do not dirty track correctly.

### ISSUE THREAD

**Issue by awood45** [awslabs/aws-sdk-ruby-record#20]
I've discovered this around set types, but it likely exists in other types too - I need to verify. Here's an example:

```ruby
require 'aws-record'

class Model
  include Aws::Record
  string_attr     :uuid, hash_key: true
  string_set_attr :problem
end

item = Model.new
item.uuid = "uuid"
item.problem = ["one"]
item.save # Initial save

from_db = Model.find(uuid: "uuid")
from_db.dirty? # => false, which is correct
from_db.problem.add("two")
from_db.dirty? # => false, which is arguably incorrect
from_db.save # Will not save the set changes.
```

The problem is that dirty tracking does not track changes to the object itself, it tracks that the object itself is different. For example, this snippet is a workaround:

```ruby
from_db = Model.find(uuid: "uuid")
from_db.problem = from_db.problem.dup.add("two")
from_db.dirty? # => true
from_db.save # properly saves the set
```

I'm working on the correct fix for this, but it should be known that this problem exists.

**Comment by ngordon17** [comment]
Hey Alex,

This was actually the expected behavior and is tested here: https://github.com/awslabs/aws-sdk-ruby-record/blob/master/spec/aws-record/record/dirty_tracking_spec.rb#L55

The correct workaround is as follows and avoids having to manually create a dup.

```

from_db = Model.find(uuid: "uuid")
from_db.dirty? # => false
from_db.problem_dirty!
from_db.dirty? # => true
 from_db.problem.add("two")
from_db.dirty? # => true
from_db.save # properly saves the set

```

However, I do agree that adding a feature to track changes to mutable objects would definitely be a better experience :D Just wanted to point out that this was not a bug, but by design

**Comment by awood45** [comment]
I understand that it was planned behavior as written, but especially when we enforce dirty updates the experience feels unintuitive. I talked with @trevorrowe and we had a solution for this in V1 which I can implement.

**Comment by ngordon17** [comment]
Awesome! That makes total sense and I agree completely.

**Comment by awood45** [comment]
#26 addresses this.
